dbs:
  - path: db/database.sqlite3
    replicas:
      - url: gcs://${BUCKET_NAME}/stockin
        retention: 24h
        retention-check-interval: 5m
        snapshot-interval: 5m
        sync-interval: 1m
