# https://dystroy.org/bacon/cookbook/#long-running-programs
[jobs.run]
command = ["cargo", "run"]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["kill", "-s", "INT"]
