services:
  app:
    build:
      context: ./
      dockerfile: docker/develop/Dockerfile
    command: ["bacon", "run"]
    environment:
      DATABASE_URL: sqlite://db/database.sqlite3
      BEARER_TOKEN: debug
    init: true
    volumes:
      - ./:/workspace
      - cargo:/usr/local/cargo/registry
      - target:/workspace/target

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  cargo:
  target:
