services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      DATABASE_URL: sqlite://db/database.sqlite3
      BEARER_TOKEN: debug
    init: true
    volumes:
      - ../:/workspace
      - cargo:/usr/local/cargo
      - target:/workspace/target

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  cargo:
  target:
