services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      DATABASE_URL: sqlite://db/database.sqlite3
    init: true
    volumes:
      - ../:/workspace
      - cargo:/usr/local/cargo
      - target:/workspace/target

volumes:
  cargo:
  target:
