services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      DATABASE_URL: postgres://root:pass@db/dev
      BEARER_TOKEN: debug
    init: true
    volumes:
      - ../:/workspace
      - cargo:/usr/local/cargo
      - target:/workspace/target

  db:
    image: postgres:16.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dev
    volumes:
      - ../db:/var/lib/postgresql/data

volumes:
  cargo:
  target:
