name: CI

on:
  push:
    branches:
      - main
      - postgres
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SQLX_OFFLINE: true
      DATABASE_URL: postgres://root:pass@localhost/dev
    services:
      db:
        image: postgres:16.6
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: dev
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable rust
        run: |
          rustup default 1.83.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build for Test
        run: |
          cargo build --tests

      - name: Test
        run: |
          cargo test

  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable rust
        run: |
          rustup default 1.83.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install components
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: rustfmt
        run: |
          cargo fmt --check

      - name: clippy
        run: |
          cargo clippy --no-deps
