name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SQLX_OFFLINE: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable rust
        run: |
          rustup default 1.83.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build for Test
        run: |
          cargo build --tests

      - name: Test
        run: |
          cargo test

  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable rust
        run: |
          rustup default 1.83.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install components
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: rustfmt
        run: |
          cargo fmt --check

      - name: clippy
        run: |
          cargo clippy --no-deps
